### ISSUE TITLE
catch all exceptions when using pip _internal?

### ISSUE THREAD

**Issue by emilburzo** [jantman/versionfinder#7]
## Bug Report

With the latest version of pip (19.2.3), `versionfinder` (and thus `awslimitchecker`) crashes when running on AWS lambda.

It is because of a recent addition to `pip`'s [subversion.py](https://github.com/pypa/pip/blob/master/src/pip/_internal/vcs/subversion.py#L191), which doesn't expect `sys.stdin` to be `None`

I've opened [an issue](https://github.com/pypa/pip/issues/7119) also at pip, but it might make sense to have a broad catch-all exceptions approach for the internal API, in `versionfinder`

**Comment by jantman** [comment]
@emilburzo Thanks, I'll definitely look into this, but it might be a little while before I can take any action on it.

Since you happened to mention it though... I was unaware (or forgot???) that anyone had gotten awslimitchecker running in Lambda. Is there any chance that you have any code you can share for packaging and/or deployment?

**Comment by emilburzo** [comment]
> I'll definitely look into this, but it might be a little while before I can take any action on it.

I think that's fine / there's no rush, affected users can either:
- pin their `pip` version
- upgrade to the newest `pip` as soon as it's out (my `pip` PR got accepted, just needs a release)

> Since you happened to mention it though... I was unaware (or forgot???) that anyone had gotten awslimitchecker running in Lambda.

Interesting, I didn't know this was problematic, for me "it just worked" :)

> Is there any chance that you have any code you can share for packaging and/or deployment?

It feels pretty basic, but if it helps someone, sure, I can put a sample repo together.

**Comment by jantman** [comment]
@emilburzo Apologies for how long it took me to get around to this. I've confirmed a fix for it in #8 and released that as [1.0.0](https://github.com/jantman/versionfinder/releases/tag/1.0.0), which is now [live on PyPI](https://pypi.org/project/versionfinder/).

Thank you so much for reporting this!

**Comment by emilburzo** [comment]
@jantman thank you!

and also very late, but here's that [example awslimitchecker-on-aws-lambda thing](https://github.com/emilburzo/awslimitchecker-aws-lambda-sample)
